// Static artwork data — used as fallback when the API isn't reachable
// (e.g. Vercel frontend before Railway backend is connected)
const staticArtworks = [
  {
    id: 1,
    title: 'Desert Solstice',
    slug: 'desert-solstice',
    description: 'A explosive celebration of color and energy capturing the spiritual power of the New Mexico desert at its peak. Bold vermillion and cadmium orange interplay with cobalt and teal in this signature Finch canvas.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Landscape & Nature',
    width_inches: 48,
    height_inches: 36,
    depth_inches: 1.5,
    year: 2023,
    price: 4200,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 1,
    is_available: 1,
    has_prints: 1,
    print_price: 185,
    image_url: '/uploads/artwork_desert_solstice.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 2,
    title: 'Spirit Reflection',
    slug: 'spirit-reflection',
    description: 'Deep crimson and emerald speak to the dialogue between earth and sky in this meditative canvas. Porter\'s 18+ years studying A Course in Miracles informs this piece\'s spiritual depth.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Spiritual & Mystical',
    width_inches: 36,
    height_inches: 36,
    depth_inches: 1.5,
    year: 2022,
    price: 3600,
    sale_price: 2880,
    is_on_sale: 1,
    is_featured: 1,
    is_available: 1,
    has_prints: 1,
    print_price: 155,
    image_url: '/uploads/artwork_spirit_reflection.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 3,
    title: 'Santa Fe Sky',
    slug: 'santa-fe-sky',
    description: 'The vast New Mexico sky at dusk — purples and golds colliding in sweeping horizontal marks that capture the infinite horizon of the high desert.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Landscape & Sky',
    width_inches: 60,
    height_inches: 40,
    depth_inches: 1.5,
    year: 2023,
    price: 5800,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 1,
    is_available: 1,
    has_prints: 1,
    print_price: 215,
    image_url: '/uploads/artwork_santa_fe_sky.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 21,
  },
  {
    id: 4,
    title: 'Cosmic Tide',
    slug: 'cosmic-tide',
    description: 'Cerulean and cobalt surge across this large-format canvas, channeling the oceanic energy Porter encountered during his time on the Pacific coast.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Ocean & Water',
    width_inches: 48,
    height_inches: 48,
    depth_inches: 2,
    year: 2021,
    price: 5200,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 195,
    image_url: '/uploads/artwork_cosmic_tide.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 5,
    title: 'Fire Dance',
    slug: 'fire-dance',
    description: 'Orange and vermillion erupt against a dark ground in this powerful statement about primal energy and creative force.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Fire & Energy',
    width_inches: 36,
    height_inches: 48,
    depth_inches: 1.5,
    year: 2023,
    price: 3900,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 1,
    is_available: 1,
    has_prints: 1,
    print_price: 165,
    image_url: '/uploads/artwork_fire_dance.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 6,
    title: 'Purple Meditation',
    slug: 'purple-meditation',
    description: 'Violet and gold — the colors of royalty and spirit — dance together in this luminous meditation. Inspired by Porter\'s long practice of A Course in Miracles.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Spiritual & Mystical',
    width_inches: 48,
    height_inches: 60,
    depth_inches: 1.5,
    year: 2022,
    price: 6500,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 225,
    image_url: '/uploads/artwork_purple_meditation.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 21,
  },
  {
    id: 7,
    title: 'Green Spirit',
    slug: 'green-spirit',
    description: 'Nature\'s life force rendered in emerald and forest green, punctuated by crimson and magenta. Porter painted this series during spring in Santa Fe.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Nature & Plants',
    width_inches: 30,
    height_inches: 40,
    depth_inches: 1.5,
    year: 2022,
    price: 2800,
    sale_price: 2240,
    is_on_sale: 1,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 135,
    image_url: '/uploads/artwork_green_spirit.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 8,
    title: 'Golden Dawn',
    slug: 'golden-dawn',
    description: 'The high desert awakens in this luminous sunrise panorama. Amber, ochre, and cadmium orange ignite the horizon while deep blue sky holds the warmth below.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Landscape & Sunrise',
    width_inches: 60,
    height_inches: 30,
    depth_inches: 1.5,
    year: 2023,
    price: 4800,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 1,
    is_available: 1,
    has_prints: 1,
    print_price: 195,
    image_url: '/uploads/artwork_golden_dawn.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 21,
  },
  {
    id: 9,
    title: 'Crimson Horizon',
    slug: 'crimson-horizon',
    description: 'A study in the power of red — how a single dominant hue can carry an entire emotional universe. Porter considers this one of his most purely emotional works.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Abstract',
    width_inches: 24,
    height_inches: 24,
    depth_inches: 1.5,
    year: 2021,
    price: 1800,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 95,
    image_url: '/uploads/artwork_spirit_reflection.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 10,
  },
  {
    id: 10,
    title: 'Blue Mesa',
    slug: 'blue-mesa',
    description: 'The iconic mesa formations of Northern New Mexico translated into pure color energy. Cool cobalt and prussian blue build layer upon layer.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Landscape',
    width_inches: 48,
    height_inches: 36,
    depth_inches: 1.5,
    year: 2020,
    price: 3400,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 145,
    image_url: '/uploads/artwork_cosmic_tide.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 11,
    title: 'Solstice Fire',
    slug: 'solstice-fire',
    description: 'Summer solstice energy captured at its peak — the longest day of the year rendered in arcs of orange and gold that spiral outward from a luminous center.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Spiritual & Ceremonial',
    width_inches: 40,
    height_inches: 40,
    depth_inches: 1.5,
    year: 2023,
    price: 4400,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 175,
    image_url: '/uploads/artwork_fire_dance.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
  {
    id: 12,
    title: 'Mystical Garden',
    slug: 'mystical-garden',
    description: 'Porter\'s love of nature and the spirit world collide in this verdant, charged canvas. Inspired by the gardens he encountered during his study-abroad year at the Sorbonne in Paris.',
    category: 'painting',
    medium: 'Mixed Media on Canvas',
    style: 'Abstract Expressionism',
    subject: 'Nature & Garden',
    width_inches: 36,
    height_inches: 48,
    depth_inches: 1.5,
    year: 2022,
    price: 3100,
    sale_price: null,
    is_on_sale: 0,
    is_featured: 0,
    is_available: 1,
    has_prints: 1,
    print_price: 135,
    image_url: '/uploads/artwork_green_spirit.png',
    ships_from: 'Santa Fe, NM',
    shipping_days: 14,
  },
];

export default staticArtworks;
